@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":VirusTrackerParser" as VirusTrackerParser LOGIC_COLOR
participant ":AddVisitCommandParser" as AddVisitCommandParser LOGIC_COLOR
participant ":AddVisitCommand" as AddVisitCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(commandText)
activate LogicManager

LogicManager -> VirusTrackerParser : parseCommand(commandText)
activate VirusTrackerParser

VirusTrackerParser -> AddVisitCommandParser : parse(args)
activate AddVisitCommandParser

AddVisitCommandParser -> AddVisitCommandParser : parseId(id)

create AddVisitCommand
AddVisitCommandParser -> AddVisitCommand
activate AddVisitCommand

AddVisitCommand --> AddVisitCommandParser : AddVisitCommand
deactivate AddVisitCommand

AddVisitCommandParser --> VirusTrackerParser : AddVisitCommand
deactivate AddVisitCommandParser

VirusTrackerParser --> LogicManager : AddVisitCommand
deactivate VirusTrackerParser

LogicManager -> AddVisitCommand : execute()
activate AddVisitCommand

AddVisitCommand -> Model : getPersonFromId(personId)
activate Model

Model --> AddVisitCommand : person
deactivate Model

AddVisitCommand -> Model : getLocationFromId(locationId)
activate Model

Model --> AddVisitCommand : location
deactivate Model

AddVisitCommand -> Model : addVisit(newVisit)
activate Model

Model --> AddVisitCommand
deactivate Model

AddVisitCommand --> LogicManager
deactivate AddVisitCommand

[<--LogicManager
deactivate LogicManager
@enduml
