@startuml
start

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

repeat :User executes command to add Visit;
repeat while () is ([incorrect args])
->[else];

:VirusTracker reads the date, and the unique identifiers for person and location;

note right
    Adding Visits can also be done using indexes but this
    diagram shows the path taken using unique identifiers.
end note

fork
    if () then ( [Person with unique identifier cannot be found] )
        :Alerts user with warning that
        Person cannot be found;
        stop
    else ( [else] )
        :Retrieve Person with specified
        unique identifier;
    endif
fork again
    if () then ( [Location with unique identifier cannot be found] )
        :Alerts user with warning that
        Location cannot be found;
        stop
    else ( [else] )
        :Retrieve Location with specified
        unique identifier;
    endif
end fork

:Creates a Visit with Person and Location;
if () then ( [Visit is made by a quarantined/infected person] )
    :Adds a warning that Visit violates
     Stay Home Notices;
else ( [else] )
endif

:Add Visit;
:Command success message is
displayed with warnings, if applicable;
note right
    Warnings may include information such
    as violations of Stay Home Notices
end note
stop

@enduml