@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":VirusTrackerParser" as VirusTrackerParser LOGIC_COLOR
participant ":DeleteVisitsCommandParser" as DeleteVisitsCommandParser LOGIC_COLOR
participant "d:DeleteVisitsCommand" as DeleteVisitsCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteVisits d/2020-02-02")
activate LogicManager

LogicManager -> VirusTrackerParser : parseCommand("deleteVisits ")
activate VirusTrackerParser

create DeleteVisitsCommandParser
 -> DeleteVisitsCommandParser
activate DeleteVisitsCommandParser

DeleteVisitsCommandParser --> VirusTrackerParser
deactivate DeleteVisitsCommandParser

VirusTrackerParser -> DeleteVisitsCommandParser : parse("d/2020-02-02")
activate DeleteVisitsCommandParser

create DeleteVisitsCommand
DeleteVisitsCommandParser -> DeleteVisitsCommand
activate DeleteVisitsCommand

DeleteVisitsCommand --> DeleteVisitsCommandParser : d
deactivate DeleteVisitsCommand

DeleteVisitsCommandParser --> VirusTrackerParser : d
deactivate DeleteVisitsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteVisitsCommandParser -[hidden]-> VirusTrackerParser
destroy DeleteVisitsCommandParser

VirusTrackerParser --> LogicManager : d
deactivate VirusTrackerParser

LogicManager -> DeleteVisitsCommand : execute()
activate DeleteVisitsCommand

DeleteVisitsCommand -> Model : deleteVisits(2020-02-02)
activate Model

Model --> DeleteVisitsCommand
deactivate Model

create CommandResult
DeleteVisitsCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteVisitsCommand
deactivate CommandResult

DeleteVisitsCommand --> LogicManager : result
deactivate DeleteVisitsCommand

[<--LogicManager
deactivate LogicManager
@enduml
