@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":VirusTrackerParser" as VirusTrackerParser LOGIC_COLOR
participant ":EditLocationCommandParser" as EditLocationCommandParser LOGIC_COLOR
participant ":EditLocationCommand" as EditLocationCommand LOGIC_COLOR
participant ":EditLocationDescriptor" as EditLocationDescriptor LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("editLocation idl/L112 n/NUS a/1 upper east cost road")
activate LogicManager

LogicManager -> VirusTrackerParser : parseCommand("editLocation idl/L112 n/Li a/1 upper east cost road")
activate VirusTrackerParser

create EditLocationCommandParser
VirusTrackerParser -> EditLocationCommandParser
activate EditLocationCommandParser

EditLocationCommandParser --> VirusTrackerParser
deactivate EditLocationCommandParser

VirusTrackerParser -> EditLocationCommandParser : parse(arguments)
activate EditLocationCommandParser

create EditLocationDescriptor
EditLocationCommandParser -> EditLocationDescriptor
activate EditLocationDescriptor

EditLocationDescriptor --> EditLocationCommandParser
deactivate EditLocationDescriptor

EditLocationCommandParser -> EditLocationDescriptor : setName(NUS)
activate EditLocationDescriptor

EditLocationDescriptor --> EditLocationCommandParser
deactivate EditLocationDescriptor

EditLocationCommandParser -> EditLocationDescriptor : setAddress(1 upper east cost road)
activate EditLocationDescriptor

EditLocationDescriptor --> EditLocationCommandParser
deactivate EditLocationDescriptor

create EditLocationCommand
EditLocationCommandParser -> EditLocationCommand
activate EditLocationCommand

EditLocationCommand --> EditLocationCommandParser : editLocationCommand
deactivate EditLocationCommand

EditLocationCommandParser --> VirusTrackerParser : editLocationCommand
deactivate EditLocationCommandParser
EditLocationCommandParser -[hidden]-> VirusTrackerParser
destroy EditLocationCommandParser

VirusTrackerParser --> LogicManager : editLocationCommand
deactivate VirusTrackerParser

LogicManager -> EditLocationCommand : execute()
activate EditLocationCommand

EditLocationCommand -> EditLocationCommand : createEditedLocation()
activate EditLocationCommand

EditLocationCommand --> EditLocationCommand : editedLocation
deactivate EditLocationCommand

EditLocationCommand -> Model : setLocation(editedLocation)
activate Model

Model --> EditLocationCommand
deactivate Model

EditLocationCommand -> Model : updateVisitBookWithEditedLocation(editedLocation)
activate Model

Model --> EditLocationCommand
deactivate Model

create CommandResult
EditLocationCommand -> CommandResult
activate CommandResult

CommandResult --> EditLocationCommand
deactivate CommandResult

EditLocationCommand --> LogicManager : result
deactivate EditLocationCommand

[<--LogicManager
deactivate LogicManager
@enduml
