@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
    Interface ReadOnlyXYZBook <<Interface>>
    Interface Model <<Interface>>
    Interface ObservableList <<Interface>>
    Class XYZBook
    Class ReadOnlyXYZBook
    Class Model
    Class ModelManager
    Class UserPrefs
    Class ReadOnlyUserPrefs

Package XYZ {
    Class XYZ
    Class UniqueXYZList
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

XYZBook .up.|> ReadOnlyXYZBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" XYZBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

XYZBook *--> "1" UniqueXYZList
UniqueXYZList o--> "*" XYZ

ModelManager -->"1" XYZ : filtered list

note as N1
    XYZ = Person,
   Location or Visit
end note

N1 .. ReadOnlyXYZBook
N1 .. XYZBook
N1 .. UniqueXYZList
N1 .. XYZ
@enduml
